firefly:
  host: "https://firefly.example.com"
  token: "test-json-web-token"
institutions:
  - name: "Chase"
    login:
      - type: navigate
        url: "https://www.chase.com/"
      - type: wait_visible
        selector: "#logonbox #login-form"
      - type: sleep
        duration: "2s"
      - type: click
        selector: "#logonbox #userId-text"
      - type: sleep
        duration: "2s"
      - type: send_keys
        selector: "#logonbox #userId-text-input-field"
        value: "username"
      - type: sleep
        duration: "2s"
      - type: send_keys
        selector: "#logonbox #password-text-input-field"
        value: "password"
      - type: sleep
        duration: "2s"
      - type: click
        selector: "#logonbox #signin-button"
      - type: sleep
        duration: "2s"
    accounts:
      - name: "Sapphire Preferred"
        firefly_account_id: 1
        account_type: "regular"
        balance:
          - type: navigate
            url: https://secure.chase.com/web/auth/dashboard#/dashboard/overview        
          - type: wait_visible
            selector: "#CARD_ACCOUNTS > div[data-testid='customAccordion-content']"
          - type: sleep
            duration: "2s"
          - type: text
            selector: "#\\31 012345678-currentBalance-dataItem > div[data-testid='dataItem-value']"